import { Category, Content, Episode, Plan, Banner, WatchHistory } from '../types/database';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Doramas', slug: 'doramas', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Filmes', slug: 'filmes', sort_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Séries', slug: 'series', sort_order: 3, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Novelas', slug: 'novelas', sort_order: 4, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-5', name: 'Novelinhas', slug: 'novelinhas', sort_order: 5, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-6', name: '+18', slug: 'mais-18', sort_order: 6, is_active: true, created_at: new Date().toISOString() },
];

export const MOCK_EPISODES: Record<string, Episode[]> = {
  'content-1': [
    {
      id: 'ep-1-1',
      content_id: 'content-1',
      season_number: 1,
      episode_number: 1,
      title: 'Episódio 1: O Retorno do Assassino Mago',
      description: 'Uma assassina de elite tem sua alma transferida para o corpo frágil de uma criada cega na terra mágica de Daeho.',
      thumbnail_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
      bunny_video_id: 'sample-bunny-ep1',
      duration: 72,
      is_published: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'ep-1-2',
      content_id: 'content-1',
      season_number: 1,
      episode_number: 2,
      title: 'Episódio 2: O Despertar do Mestre',
      description: 'Jang Uk descobre o segredo de Mu-deok e implora para que ela se torne sua mestra secreta nas artes místicas.',
      thumbnail_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
      bunny_video_id: 'sample-bunny-ep2',
      duration: 68,
      is_published: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'ep-1-3',
      content_id: 'content-1',
      season_number: 1,
      episode_number: 3,
      title: 'Episódio 3: O Teste de Jeonjingak',
      description: 'Confrontos políticos e intrigas surgem entre as famílias nobres enquanto a energia espiritual de Uk começa a despertar.',
      thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
      bunny_video_id: 'sample-bunny-ep3',
      duration: 75,
      is_published: true,
      created_at: new Date().toISOString(),
    },
  ],
  'content-2': [
    {
      id: 'ep-2-1',
      content_id: 'content-2',
      season_number: 1,
      episode_number: 1,
      title: 'Episódio 1: Pouso Forçado no Norte',
      description: 'Um acidente de parapente leva uma herdeira sul-coreana bilionária para o outro lado da fronteira, nos braços de um oficial militar.',
      thumbnail_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
      bunny_video_id: 'sample-bunny-cly-1',
      duration: 70,
      is_published: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 'ep-2-2',
      content_id: 'content-2',
      season_number: 1,
      episode_number: 2,
      title: 'Episódio 2: O Disfarce de Noiva',
      description: 'Ri Jeong-hyeok apresenta Se-ri aos vizinhos e aldeões como sua noiva secreta para evitar que ela seja descoberta pela patrulha.',
      thumbnail_url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&auto=format&fit=crop&q=80',
      bunny_video_id: 'sample-bunny-cly-2',
      duration: 74,
      is_published: true,
      created_at: new Date().toISOString(),
    },
  ]
};

export const MOCK_CONTENTS: Content[] = [
  {
    id: 'content-1',
    title: 'Alquimia das Almas',
    slug: 'alquimia-das-almas',
    description: 'Uma poderosa feiticeira presa no corpo de uma mulher cega é contratada por um nobre prestigiado para ajudá-lo a mudar seu destino no reino místico de Daeho.',
    category_id: 'cat-1',
    cover_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-alquimia-01',
    year: 2023,
    rating: 9.8,
    duration: 70,
    classification: '14',
    country: 'Coreia do Sul',
    language: 'Legendado / Dublado',
    is_featured: true,
    is_trending: true,
    is_published: true,
    legacy_id: 'leg-101',
    legacy_video_url: 'https://oldcdn.doramas.com/videos/alquimia-almas.mp4',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-2',
    title: 'Pousando no Amor',
    slug: 'pousando-no-amor',
    description: 'Após um acidente de parapente, uma rica herdeira sul-coreana cai na Coreia do Norte e encontra abrigo na casa de um nobre oficial do exército.',
    category_id: 'cat-1',
    cover_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-pousando-01',
    year: 2022,
    rating: 9.9,
    duration: 80,
    classification: '12',
    country: 'Coreia do Sul',
    language: 'Dublado',
    is_featured: true,
    is_trending: true,
    is_published: true,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-3',
    title: 'Vincenzo: O Advogado da Máfia',
    slug: 'vincenzo',
    description: 'Ao visitar sua terra natal, um advogado coreano-italiano da máfia se envolve em uma guerra contra um conglomerado farmacêutico impiedoso.',
    category_id: 'cat-1',
    cover_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-vincenzo-01',
    year: 2023,
    rating: 9.7,
    duration: 85,
    classification: '16',
    country: 'Coreia do Sul',
    language: 'Legendado / Dublado',
    is_featured: true,
    is_trending: false,
    is_published: true,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-4',
    title: 'A Lição (The Glory)',
    slug: 'a-licao',
    description: 'Anos após sobreviver a terríveis abusos no ensino médio, uma mulher arquiteta um meticuloso plano de vingança contra seus carrascos.',
    category_id: 'cat-3',
    cover_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-glory-01',
    year: 2023,
    rating: 9.6,
    duration: 55,
    classification: '16',
    country: 'Coreia do Sul',
    language: 'Dublado',
    is_featured: false,
    is_trending: true,
    is_published: true,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-5',
    title: 'Parasita: A Linha Vermelha',
    slug: 'parasita-filme',
    description: 'Toda a família de Ki-taek está desempregada, vivendo num porão sujo e precário. Uma oportunidade muda tudo quando o filho começa a dar aulas para os herdeiros de uma família rica.',
    category_id: 'cat-2',
    cover_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-parasite-movie',
    year: 2020,
    rating: 9.9,
    duration: 132,
    classification: '16',
    country: 'Coreia do Sul',
    language: 'Legendado',
    is_featured: false,
    is_trending: true,
    is_published: true,
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-6',
    title: 'A Promessa do Dragão',
    slug: 'a-promessa-do-dragao',
    description: 'Uma épica novela oriental retratando o amor proibido entre uma deusa imortal da lua e o general do exército imperial da dinastia Tang.',
    category_id: 'cat-4',
    cover_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-novela-dragao',
    year: 2024,
    rating: 9.4,
    duration: 48,
    classification: '12',
    country: 'China',
    language: 'Legendado',
    is_featured: false,
    is_trending: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-7',
    title: 'Meu Doce Chefe Secreto',
    slug: 'meu-doce-chefe-secreto',
    description: 'Micro-drama romântico de episódios rápidos sobre uma assistente executiva que descobre a vida dupla do presidente de sua empresa.',
    category_id: 'cat-5',
    cover_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-novelinha-chefe',
    year: 2024,
    rating: 9.1,
    duration: 15,
    classification: '10',
    country: 'Coreia do Sul',
    language: 'Legendado',
    is_featured: false,
    is_trending: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-8',
    title: 'Desejo Noturno em Gangnam',
    slug: 'desejo-noturno-em-gangnam',
    description: 'Thriller erótico e psicológico envolvendo a alta sociedade, disputas de poder, segredos inconfessáveis e paixões ardentes.',
    category_id: 'cat-6',
    cover_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-plus18-gangnam',
    year: 2024,
    rating: 9.3,
    duration: 110,
    classification: '18',
    country: 'Coreia do Sul',
    language: 'Legendado',
    is_featured: false,
    is_trending: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'content-9',
    title: 'Itaewon Class: A Revolta',
    slug: 'itaewon-class',
    description: 'Em um bairro vibrante de Seul, um jovem ex-presidiário e seus amigos leais lutam para transformar seu pequeno bar num império da gastronomia.',
    category_id: 'cat-1',
    cover_url: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=500&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1600&auto=format&fit=crop&q=80',
    bunny_video_id: 'bunny-itaewon-01',
    year: 2021,
    rating: 9.8,
    duration: 72,
    classification: '14',
    country: 'Coreia do Sul',
    language: 'Dublado',
    is_featured: true,
    is_trending: true,
    is_published: true,
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'Alquimia das Almas',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1800&auto=format&fit=crop&q=80',
    content_id: 'content-1',
    sort_order: 1,
    is_active: true,
    starts_at: new Date().toISOString(),
    ends_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'banner-2',
    title: 'Pousando no Amor',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1800&auto=format&fit=crop&q=80',
    content_id: 'content-2',
    sort_order: 2,
    is_active: true,
    starts_at: new Date().toISOString(),
    ends_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'banner-3',
    title: 'Vincenzo: O Advogado da Máfia',
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1800&auto=format&fit=crop&q=80',
    content_id: 'content-3',
    sort_order: 3,
    is_active: true,
    starts_at: new Date().toISOString(),
    ends_at: null,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_PLANS: Plan[] = [
  {
    id: 'plan-1',
    name: 'Mensal Premium',
    description: 'Acesso ilimitado a todo o catálogo em Full HD, sem anúncios, em até 2 telas simultâneas.',
    price: 19.90,
    billing_period: 'monthly',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'plan-2',
    name: 'Trimestral VIP',
    description: 'Mais economia! Resolução 4K Ultra HD com HDR, 3 telas simultâneas e lançamentos antecipados.',
    price: 49.90,
    billing_period: 'quarterly',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'plan-3',
    name: 'Anual Diamond',
    description: 'O melhor custo-benefício! 4 telas em 4K Ultra HD, downloads para assistir offline e suporte prioritário VIP.',
    price: 149.90,
    billing_period: 'yearly',
    is_active: true,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_CONTINUE_WATCHING: WatchHistory[] = [
  {
    id: 'wh-1',
    user_id: 'user-default',
    content_id: 'content-1',
    content: MOCK_CONTENTS[0],
    episode_id: 'ep-1-1',
    episode: MOCK_EPISODES['content-1'][0],
    progress_seconds: 1850,
    duration_seconds: 4320,
    percentage: 42.8,
    completed: false,
    last_watched_at: new Date().toISOString(),
  },
  {
    id: 'wh-2',
    user_id: 'user-default',
    content_id: 'content-2',
    content: MOCK_CONTENTS[1],
    episode_id: 'ep-2-1',
    episode: MOCK_EPISODES['content-2'][0],
    progress_seconds: 3200,
    duration_seconds: 4200,
    percentage: 76.2,
    completed: false,
    last_watched_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  }
];
